/*
* generated by Xtext
*/
package org.grassaccords.emqcfg.contentassist;

import org.grassaccords.emqcfg.contentassist.AbstractMQCfgProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class MQCfgProposalProvider extends AbstractMQCfgProposalProvider {

}
