/*
 * generated by Xtext
 */
package org.grassaccords.emqcfg.scoping;

import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.ecore.EReference;
import org.eclipse.xtext.scoping.IScope;
import org.eclipse.xtext.scoping.Scopes;
import org.eclipse.xtext.scoping.impl.AbstractDeclarativeScopeProvider;
import org.eclipse.xtext.scoping.impl.SimpleScope;
import org.grassaccords.emqcfg.mQCfg.ClusterQMgrBinding;
import org.grassaccords.emqcfg.mQCfg.Interface;
import org.grassaccords.emqcfg.mQCfg.QMgr;
import org.grassaccords.emqcfg.mQCfg.QMgrBinding;

/**
 * This class contains custom scoping description.
 * 
 * see : http://www.eclipse.org/Xtext/documentation/latest/xtext.html#scoping on
 * how and when to use it
 * 
 */
public class MQCfgScopeProvider extends AbstractDeclarativeScopeProvider {

	IScope scope_QMgrBinding_interface(QMgrBinding qMgrBinding, EReference ref) {
		QMgr qmgr = qMgrBinding.getQmgr();
		EList<Interface> interfaces = qmgr.getInterfaces();
		return createScope(interfaces);
	}

	IScope scope_ClusterQMgrBinding_interface(ClusterQMgrBinding clusterQMgrBinding, EReference ref) {
		QMgr qmgr = clusterQMgrBinding.getQmgr();
		EList<Interface> interfaces = qmgr.getInterfaces();
		return createScope(interfaces);
	}

	private IScope createScope(EList<Interface> interfaces) {
		return new SimpleScope(Scopes.scopedElementsFor(interfaces));
	}

}
