/*
 * generated by Xtext
 */
package org.grassaccords.emqcfg;

/**
 * Use this class to register components to be used within the IDE.
 */
public class MQCfgUiModule extends org.grassaccords.emqcfg.AbstractMQCfgUiModule {

}
