/*
 * generated by Xtext
 */
package org.grassaccords.emqcfg.outline;

import java.util.ArrayList;
import java.util.List;

import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.ui.common.editor.outline.ContentOutlineNode;
import org.eclipse.xtext.ui.common.editor.outline.transformer.AbstractDeclarativeSemanticModelTransformer;
import org.grassaccords.emqcfg.mQCfg.ClusterQMgrBinding;
import org.grassaccords.emqcfg.mQCfg.Node;

/**
 * customization of the default outline structure
 * 
 */
public class MQCfgTransformer extends
		AbstractDeclarativeSemanticModelTransformer {

	public ContentOutlineNode createNode(Node semanticNode,
			ContentOutlineNode parentNode) {
		ContentOutlineNode node = super
				.newOutlineNode(semanticNode, parentNode);
		return node;
	}

	public List<EObject> getChildren(Node node) {
		return new ArrayList<EObject>(node.getQmgrs());
	}

	public ContentOutlineNode createNode(ClusterQMgrBinding semanticNode,
			ContentOutlineNode parentNode) {
		ContentOutlineNode node = super
				.newOutlineNode(semanticNode, parentNode);
		return node;
	}

	public List<EObject> getChildren(ClusterQMgrBinding clusterQMgrBinding) {
		ArrayList<EObject> arrayList = new ArrayList<EObject>();
		arrayList.add(clusterQMgrBinding.getInterface());
		return arrayList;
	}
}
